server:
  port: 8088
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://rm-bp13q0jl95pd4zo279o.mysql.rds.aliyuncs.com:3306/content-center
    hikari:
      username: wzw
      password: cM8E!c_89iz2LKV
      driver-class-name: com.mysql.cj.jdbc.Driver
  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
