server:
  port: 8888
spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://rm-uf6m7500g66x1ms64eo.mysql.rds.aliyuncs.com:3306/content-center
    hikari:
      username: wanghuanle
      password: wanghuanle
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

ribbon:
  eager-load:
    enabled: true
    clients: user-center


logging:
  level:
    com.soft1851.contentcenter.feignclient.UserCenterFeignClient: debug
