server:
  port: 8001 #当前的EurekaClient服务端口
# 服务注册
info:
  app:
    name: provider-hello111  #当前服务再acruator监控中的应用名称
#    version:1.0.0
spring:
  application:
    name: provider-hello #当前服务注册再Eureka Server的名称
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details:always
#    shutdown:
#      enabled: true
eureka:
  instance:
    hostname: wanghuanle.com #主机名
    profer-ippaddress: true #是否将当前服务的Ip注册到Eureka Server
  client:
    #    fetch-registry: true
    #    register-with-eureka: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/